title: "phinze's home page"
url: https://phinze.com
logo: /assets/images/logo.png

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  talks:
    output: true
  projects:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: "/writing/:title"
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      permalink: "/speaking/:title"
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: "/projects/:title"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
