name: "&ldquo;...so create&rdquo;"
description: Paul Hinze writes stuff here
url: http://phinze.github.io
author: Paul Hinze
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
pygments: true
