
title: "&ldquo;...so create&rdquo;"
description: Paul Hinze writes stuff here
tagline: Paul Hinze writes stuff here

url: https://phinze.blog
remote_theme: "mmistakes/minimal-mistakes@4.19.1"

logo: /assets/images/logo.png

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Paul Hinze"
  avatar : "/assets/images/bio-photo.png"
  bio    : "A human."
  twitter: "phinze"
  github:  "phinze"
  links:
    - icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/phinze"
    - icon: "fab fa-fw fa-github"
      url: "https://github.com/phinze"


include: ["_pages"]

collections:
  talks:
    output: true
    permalink: /:collection/:path/

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      permalink: "/posts/:title"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: false
